srm_core_organisation_create:
    path:       /organisations
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmCoreBundle:Organisation:info"

srm_core_organisation_info:
    path:       /organisations/{organisationId}
    methods:    [GET]
    defaults:
        _controller:    "SrmCoreBundle:Organisation:info"

srm_core_organisation_delete:
    path:       /organisations/{organisationId}
    methods:    [DELETE]
    defaults:
        _controller:    "SrmCoreBundle:Organisation:delete"
