srm_core_organisation_show:
    path:       /organisations/{organisationId}
    methods:    [GET]
    defaults:
        _controller:    "SrmCoreBundle:Organisation:show"

srm_core_organisation_basic:
    path:       /organisations/{organisationId}/basic
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmCoreBundle:Organisation:basic"
        organisationId: 42

srm_core_organisation_legal:
    path:       /organisations/{organisationId}/legal
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmCoreBundle:Organisation:legal"
