srm_indicator_data_list:
    path:       /organisations/{organisationId}/data
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Data:list"

srm_indicator_data_add:
    path:       /organisations/{organisationId}/data/add
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Data:form"

srm_indicator_data_show:
    path:       /organisations/{organisationId}/data/{dataId}/show
    methods:    [GET]
    defaults:
        _controller:    "SrmIndicatorBundle:Data:show"
    requirements:
        dataId: \d+

srm_indicator_data_disable:
    path:       /organisations/{organisationId}/data/{dataId}/disable
    methods:    [GET]
    defaults:
        _controller:    "SrmIndicatorBundle:Data:disable"
    requirements:
        dataId: \d+

srm_indicator_data_edit:
    path:       /organisations/{organisationId}/data/{dataId}
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Data:form"
    requirements:
        dataId: \d+