srm_website_departments_list:
    path:       /organisations/{organisationId}/departments
    methods:    [GET]
    defaults:
        _controller:    "SrmWebsiteBundle:Departments:list"

srm_website_departments_add:
    path:       /organisations/{organisationId}/departments/add
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmWebsiteBundle:Departments:form"

srm_website_department_show:
    path:       /organisations/{organisationId}/departments/{departmentId}/show
    methods:    [GET]
    defaults:
        _controller:    "SrmWebsiteBundle:Departments:show"
    requirements:
        departmentId: \d+

srm_website_department_disable:
    path:       /organisations/{organisationId}/departments/{departmentId}/disable
    methods:    [GET]
    defaults:
        _controller:    "SrmWebsiteBundle:Departments:disable"
    requirements:
        departmentId: \d+

srm_website_department_edit:
    path:       /organisations/{organisationId}/departments/{departmentId}
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmWebsiteBundle:Departments:form"
    requirements:
        departmentId:   \d+
