srm_indicator_indicator_list:
    path:       /organisations/{organisationId}/indicator
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Indicator:list"

srm_indicator_indicator_add:
    path:       /organisations/{organisationId}/indicator/add
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Indicator:form"

srm_indicator_indicator_show:
    path:       /organisations/{organisationId}/indicator/{indicatorId}/show
    methods:    [GET]
    defaults:
        _controller:    "SrmIndicatorBundle:Indicator:show"
    requirements:
        indicatorId: \d+

srm_indicator_indicator_disable:
    path:       /organisations/{organisationId}/indicator/{indicatorId}/disable
    methods:    [GET]
    defaults:
        _controller:    "SrmIndicatorBundle:Indicator:disable"
    requirements:
        indicatorId: \d+


srm_indicator_indicator_edit:
    path:       /organisations/{organisationId}/indicator/{indicatorId}
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Indicator:form"
    requirements:
        indicatorId: \d+

indicators_by_categories:
    path:       /organisations/{organisationId}/indicators/by_categories
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Indicator:indicatorsByCategories"
    requirements:
        indicatorId: \d+