srm_indicator_referencial_list:
    path:       /organisations/{organisationId}/referencials
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Referencials:list"

srm_indicator_referencial_add:
    path:       /organisations/{organisationId}/referencials/add
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Referencials:form"

srm_indicator_referencial_show:
    path:       /organisations/{organisationId}/referencials/{referencialId}/show
    methods:    [GET]
    defaults:
        _controller:    "SrmIndicatorBundle:Referencials:show"
    requirements:
        referencialId: \d+

srm_indicator_referencial_disable:
    path:       /organisations/{organisationId}/referencials/{referencialId}/disable
    methods:    [GET]
    defaults:
        _controller:    "SrmIndicatorBundle:Referencials:disable"
    requirements:
        referencialId: \d+

srm_indicator_referencial_edit:
    path:       /organisations/{organisationId}/referencials/{referencialId}
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Referencials:form"
    requirements:
        referencialId: \d+

indicators_by_categories:
    path:       /organisations/{organisationId}/indicators/by_categories
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Referencials:indicatorsByCategories"
    requirements:
        referencialId: \d+

category1_by_referencialType:
    path:       /organisations/{organisationId}/category1/by_referencialType
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Referencials:category1ByReferencialType"
    requirements:
        referencialId: \d+

category2_by_category1:
    path:       /organisations/{organisationId}/category2/by_category1
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Referencials:category2ByCategory1"
    requirements:
        referencialId: \d+

category3_by_category2:
    path:       /organisations/{organisationId}/category3/by_category2
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Referencials:category3ByCategory2"
    requirements:
        referencialId: \d+