srm_indicator_repository_list:
    path:       /organisations/{organisationId}/repositories
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Repositories:list"

srm_indicator_repository_add:
    path:       /organisations/{organisationId}/repositories/add
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Repositories:form"

srm_indicator_repository_show:
    path:       /organisations/{organisationId}/repositories/{repositoryId}/show
    methods:    [GET]
    defaults:
        _controller:    "SrmIndicatorBundle:Repositories:show"
    requirements:
        repositoryId: \d+

srm_indicator_repository_disable:
    path:       /organisations/{organisationId}/repositories/{repositoryId}/disable
    methods:    [GET]
    defaults:
        _controller:    "SrmIndicatorBundle:Repositories:disable"
    requirements:
        repositoryId: \d+

srm_indicator_repository_edit:
    path:       /organisations/{organisationId}/repositories/{repositoryId}
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Repositories:form"
    requirements:
        repositoryId: \d+

# Liste déroulante des indicateurs
indicators_by_categories:
    path:       /organisations/{organisationId}/indicators/by_categories
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmIndicatorBundle:Repositories:indicatorsByCategories"
    requirements:
        repositoryId: \d+