srm_website_sites_list:
    path:       /organisations/{organisationId}/sites
    methods:    [GET]
    defaults:
        _controller:    "SrmWebsiteBundle:Sites:list"

srm_website_sites_add:
    path:       /organisations/{organisationId}/sites/add
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmWebsiteBundle:Sites:form"

srm_website_sites_edit:
    path:       /organisations/{organisationId}/sites/{siteId}
    methods:    [GET,POST]
    defaults:
        _controller:    "SrmWebsiteBundle:Sites:form"
    requirements:
        siteId: \d+
