_organisations:
    resource: "routing/organisations.yml"
_sites:
    resource: "routing/sites.yml"
_departments:
    resource: "routing/departments.yml"
_contacts:
    resource: "routing/contacts.yml"
_poles:
    resource: "routing/poles.yml"
