_organisations:
    resource: "routing/organisations.yml"
_sites:
    resource: "routing/sites.yml"
_departments:
    resource: "routing/departments.yml"
_contacts:
    resource: "routing/contacts.yml"
_users:
    resource: "routing/users.yml"
_poles:
    resource: "routing/poles.yml"
_groupStakeholder:
    resource: "routing/groupStakeholder.yml"
_stakeholder:
    resource: "routing/stakeholder.yml"
_shareholders:
    resource: "routing/shareholders.yml"
_referencials:
    resource: "routing/referencials.yml"
_indicator:
    resource: "routing/indicator.yml"
_item:
    resource: "routing/items.yml"