_organisations:
    resource: "@SrmWebsiteBundle/Resources/config/routing/organisations.yml"
_sites:
    resource: "@SrmWebsiteBundle/Resources/config/routing/sites.yml"
_departments:
    resource: "@SrmWebsiteBundle/Resources/config/routing/departments.yml"
