Srm\CoreBundle\Entity\Contact:
  properties:
    gender:
        - Valid: ~
    firstname:
        - NotBlank: ~
    lastname:
        - NotBlank: ~
    mail:
        - NotBlank: ~
        - Email: { message: "L'adresse {{ value }} n'est pas valide", checkMX: true }
    contactFunction:
        - NotBlank: ~
    mobilePhone:
        - NotBlank: ~
    role:
        - Valid: ~
    address:
        - Valid: ~
    departments:
        - Collection:
            fields:
                label:
                  - NotBlank: ~
            allowExtraFields: false

Srm\CoreBundle\Entity\Site:
  properties:
    language:
        - NotBlank: ~
        - Language: { message: "La langue {{ value }} n'est pas valide", checkMX: true }

Srm\CoreBundle\Entity\Gender:
  properties:
    label:
        - NotBlank: ~
    shortLabel:
        - NotBlank: ~
    genderId:
        - NotBlank: ~


Srm\UserBundle\Entity\Role:
  properties:
    label:
        - NotBlank: ~

Srm\CoreBundle\Entity\Stakeholder:
  properties:
    label:
        - NotBlank: ~
    siretNumber:
        - NotBlank: ~
    firstname:
        - NotBlank: ~
    lastname:
        - NotBlank: ~
    email:
        - NotBlank: ~
        - Email: { message: "L'adresse {{ value }} n'est pas valide", checkMX: true }